apiVersion: v1
kind: Service
metadata:
  name: spring-critical-api-service
  labels:
    app: spring-critical-api
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: spring-critical-api
