apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  # DB/Redis 접속 정보
  DB_PORT: "5432"
  DB_NAME: "postgres"
  # REDIS_HOST: "my-redis.internal"
  # REDIS_PORT: "6379"
  
  # 앱 상세 설정
  JPA_DDL_AUTO: "update"
  JPA_SHOW_SQL: "true"
  CORS_ALLOWED_ORIGINS: "https://olive0.store"