apiVersion: v1
kind: Service
metadata:
  name: python-critical-ai-api-svc
  labels:
    app: python-critical-ai-api
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: python-critical-ai-api
