# 기존 설정 유지
mode: deployment
image:
  repository: otel/opentelemetry-collector-contrib

config:
  exporters:
    debug:
      verbosity: detailed
    otlp:
      endpoint: tempo.monitoring.svc.cluster.local:4317
      tls:
        insecure: true
  service:
    pipelines:
      traces:
        exporters:
          - otlp
          - debug
        receivers:
          - otlp

# # 이사 설정 추가 (가장 아래에 붙이세요)
# nodeSelector:
#   karpenter.sh/nodepool: monitoring

# tolerations:
#   - key: "workload"
#     operator: "Equal"
#     value: "monitoring"
#     effect: "NoSchedule"
